@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@scheme = http
@rootUrl = {{scheme}}://{{host}}
@version = 1
@apiUrl = {{rootUrl}}/api/v{{version}}

###

GET {{apiUrl}}/games/
content-type: application/json
Accept: application/json
X-DEV-API-KEY: 958dbf6c-a623-4baa-8be9-a44dd3c69bbd

###

GET {{apiUrl}}/games/1/
content-type: application/json
Accept: application/json
X-DEV-API-KEY: 958dbf6c-a623-4baa-8be9-a44dd3c69bbd

###

GET {{apiUrl}}/game-statistics/1/
content-type: application/json
Accept: application/json
X-DEV-API-KEY: 958dbf6c-a623-4baa-8be9-a44dd3c69bbd

###

GET {{apiUrl}}/my-reviews/
content-type: application/json
Accept: application/json
X-DEV-API-KEY: 958dbf6c-a623-4baa-8be9-a44dd3c69bbd

###

GET {{apiUrl}}/game-reviews/
content-type: application/json
Accept: application/json
X-DEV-API-KEY: 958dbf6c-a623-4baa-8be9-a44dd3c69bbd

###

GET {{apiUrl}}/game-reviews/1/
content-type: application/json
Accept: application/json
X-DEV-API-KEY: 958dbf6c-a623-4baa-8be9-a44dd3c69bbd
