# Generated by Django 2.1.3 on 2018-12-13 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_developer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField(unique=True)),
                ('price', models.FloatField()),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='rest_api.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Category')),
                ('game_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='LoadState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.BooleanField(default=False)),
                ('times_played', models.IntegerField()),
                ('score', models.BigIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_player', models.BooleanField(default=True)),
                ('games', models.ManyToManyField(through='rest_api.PlayDetails', to='rest_api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='rest_api.Game')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Player')),
            ],
        ),
        migrations.AddField(
            model_name='playdetails',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Player'),
        ),
    ]
