# Generated by Django 2.1.3 on 2018-12-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='gamecategory',
            old_name='game_id',
            new_name='game',
        ),
    ]
