# Generated by Django 2.1.3 on 2019-01-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
    ]
