# Generated by Django 2.1.3 on 2018-12-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('dev_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
