# Generated by Django 2.1.3 on 2018-12-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('dev_api', '0002_apikeys_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApiKeys',
            new_name='ApiKey',
        ),
    ]
