# Generated by Django 2.1.3 on 2019-01-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_api', '0003_auto_20181223_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apikey', to='user.Profile'),
        ),
    ]
