# Generated by Django 2.1.3 on 2019-01-25 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dev_api', '0004_auto_20190125_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='apikey', serialize=False, to='user.Profile'),
        ),
    ]
