GET http://localhost:8000/api/dev/
content-type: application/json

{
    "id": 1
}

###

PUT http://localhost:8000/api/dev/
content-type: application/json

{
    "username": "JohnDoe",
    "password": "foobar",
    "email": "address@example.com"
}

### 

POST http://localhost:8000/api/dev/
content-type: application/json
# Authorization: 

{
    "id": 1,
    "username": "DoeJohn",
    "email": "example@address.com"
}


