# Generated by Django 2.1.3 on 2019-01-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190110_1049'),
        ('game', '0003_auto_20190109_1413'),
    ]

    operations = [
    ]
