# Generated by Django 2.1.3 on 2019-01-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190110_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
