# Generated by Django 2.1.3 on 2019-01-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_merge_20190110_1936'),
        ('game', '0006_auto_20190110_1926'),
    ]

    operations = [
    ]
