# Generated by Django 2.1.3 on 2019-01-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_merge_20190115_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='ref',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
