# Generated by Django 2.1.3 on 2019-01-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_email_confirmed'),
        ('game', '0009_auto_20190115_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('game', 'created_by')},
        ),
    ]
