# Generated by Django 2.1.3 on 2019-01-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_email_confirmed'),
        ('game', '0010_auto_20190116_1123'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('game', 'user')},
        ),
    ]
