# Generated by Django 2.1.3 on 2019-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20190117_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='content',
            field=models.BinaryField(),
        ),
    ]
