# Generated by Django 2.1.3 on 2019-01-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20190117_1356'),
        ('game', '0013_game_updated_at'),
    ]

    operations = [
    ]
