# Generated by Django 2.1.3 on 2019-01-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_merge_20190120_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='user.Profile'),
        ),
    ]
