# Generated by Django 2.1.3 on 2019-01-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20190122_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='game.Game'),
        ),
    ]
